# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "圣代菌"
email = "cybeird@outlook.com"
link = "https://sundedi.github.io/"
avatar = "/images/avatar.png"
